export const tags = {
  CONST_TAG_NEW: 'NEW',
  CONST_TAG_BEST: 'BEST',
  CONST_TAG_LIVING: 'LIVING',
  CONST_TAG_KITCHEN: 'KITCHEN',
  CONST_TAG_STATIONERY: 'STATIONERY',
  CONST_TAG_BABYKIDS: 'BABY/KIDS',
  CONST_TAG_TABLE: 'TABLE',
  CONST_TAG_ROOM: 'ROOM',
  CONST_TAG_LIGHT: 'LIGHT',
  CONST_TAG_BED: 'BED',
  CONST_TAG_CUP: 'CUP',
  CONST_TAG_DISHES: 'DISHES',
  CONST_TAG_PLATE: 'PLATE',
  CONST_TAG_GOODS: 'GOODS',
  CONST_TAG_CUTTING_BOARD: 'CUTTING_BOARD'
}
